CREATE DATABASE teste;

USE teste;

CREATE TABLE R(
	A VARCHAR(2)
);

CREATE TABLE S(
	A VARCHAR(2)
);

INSERT INTO R(A) VALUES ('a1'),('a2'),('a2'),('a3');
INSERT INTO S(A) VALUES ('a1'),('a1'),('a2'),('a2'),('a2'),('a3'),('a4'),('a5');

SELECT * FROM R;
SELECT * FROM S;

-- Except -> NOT IN
SELECT * FROM S WHERE A NOT IN (SELECT A FROM R);

-- UNION
(SELECT DISTINCT R.A FROM R)
	UNION
(SELECT DISTINCT S.A FROM S);

-- INTERSECT -> IN
SELECT R.A FROM R WHERE R.A IN (SELECT S.A FROM S);
SELECT DISTINCT R.A FROM R WHERE R.A IN (SELECT S.A FROM S);